# Generated by Django 5.0.7 on 2026-02-04 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('codigo_hex', models.CharField(blank=True, help_text='Código de color en formato hexadecimal (#RRGGBB)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Formato hexadecimal inválido')])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'acceso_vehicular_color',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puerta de Acceso',
                'verbose_name_plural': 'Puertas de Acceso',
                'db_table': 'acceso_vehicular_puerta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono (opcional)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículo',
                'db_table': 'acceso_vehicular_tipo_vehiculo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('placa', models.CharField(db_index=True, help_text='Número de placa del vehículo', max_length=15)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen capturada del vehículo', null=True, upload_to='acceso_vehicular/imagenes/%Y/%m/%d/')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='acceso_vehicular.color')),
                ('guardia', models.ForeignKey(help_text='Guardia que registró el acceso', on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='acceso_vehicular.puerta')),
                ('tipo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='acceso_vehicular.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'acceso_vehicular_registro',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_detectado', models.BooleanField(default=False)),
                ('confianza_deteccion', models.FloatField(blank=True, help_text='Confianza de detección del vehículo (0-1)', null=True)),
                ('clase_detectada', models.CharField(blank=True, help_text='Clase detectada por YOLO (car, truck, motorcycle, etc.)', max_length=50)),
                ('placa_detectada', models.CharField(blank=True, max_length=15)),
                ('confianza_ocr', models.FloatField(blank=True, help_text='Confianza del OCR (0-1)', null=True)),
                ('color_detectado', models.CharField(blank=True, max_length=30)),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del procesamiento (bounding boxes, tiempos, etc.)')),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('tiempo_procesamiento_ms', models.IntegerField(blank=True, help_text='Tiempo de procesamiento en milisegundos', null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_ocr', to='acceso_vehicular.registroacceso')),
            ],
            options={
                'verbose_name': 'Resultado OCR',
                'verbose_name_plural': 'Resultados OCR',
                'db_table': 'acceso_vehicular_resultado_ocr',
            },
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['fecha_hora', 'puerta'], name='acceso_vehi_fecha_h_eda2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['placa', 'fecha_hora'], name='acceso_vehi_placa_705054_idx'),
        ),
    ]
